ta: es una biblioteca que proporciona una amplia variedad de indicadores técnicos para el análisis de estrategias de trading. Algunos de los indicadores que se pueden calcular con ta incluyen el RSI, el MACD, el promedio móvil, entre otros.

backtrader: es una biblioteca de backtesting de estrategias de trading. Permite simular estrategias de trading en datos históricos y evaluar su desempeño.

zipline: es una biblioteca de backtesting y trading algorítmico. Permite la creación de estrategias de trading y su ejecución en tiempo real o en datos históricos.

In [11]:
import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt
from ta import add_all_ta_features
from ta.utils import dropna
from ta.volatility import BollingerBands

In [9]:
df = yf.download(tickers = "SPY",  # list of tickers
            period = "50y",         # time period
            interval = "1d",       # trading interval
            ignore_tz = True,      # ignore timezone when aligning data from different exchanges?
            prepost = False)       # download pre/post market hours data?

[*********************100%***********************]  1 of 1 completed

In [12]:
# Clean NaN values
df = dropna(df)

# Initialize Bollinger Bands Indicator
indicator_bb = BollingerBands(close=df["Close"], window=20, window_dev=2)

# Add Bollinger Bands features
df['bb_bbm'] = indicator_bb.bollinger_mavg()
df['bb_bbh'] = indicator_bb.bollinger_hband()
df['bb_bbl'] = indicator_bb.bollinger_lband()

# Add Bollinger Band high indicator
df['bb_bbhi'] = indicator_bb.bollinger_hband_indicator()

# Add Bollinger Band low indicator
df['bb_bbli'] = indicator_bb.bollinger_lband_indicator()

In [13]:
df

,Open,High,Low,Close,Adj Close,Volume,bb_bbm,bb_bbh,bb_bbl,bb_bbhi,bb_bbli
Date,,,,,,,,,,,
1993-01-29,43.968750,43.968750,43.750000,43.937500,25.218233,1003200,NaN,NaN,NaN,0.0,0.0
1993-02-01,43.968750,44.250000,43.968750,44.250000,25.397596,480500,NaN,NaN,NaN,0.0,0.0
1993-02-02,44.218750,44.375000,44.125000,44.343750,25.451395,201300,NaN,NaN,NaN,0.0,0.0
1993-02-03,44.406250,44.843750,44.375000,44.812500,25.720419,529400,NaN,NaN,NaN,0.0,0.0
1993-02-04,44.968750,45.093750,44.468750,45.000000,25.828054,531500,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2023-03-01,395.410004,396.690002,393.380005,394.739990,394.739990,99706800,406.456001,420.436143,392.475860,0.0,0.0
2023-03-02,392.679993,398.690002,392.329987,397.809998,397.809998,85127800,405.806502,420.122003,391.491000,0.0,0.0
2023-03-03,399.709991,404.450012,399.029999,404.190002,404.190002,90038300,405.177002,418.585491,391.768512,0.0,0.0
2023-03-06,405.049988,407.450012,404.010010,404.470001,404.470001,72689600,404.783002,417.782087,391.783916,0.0,0.0
2023-03-07,404.420013,404.670013,397.880005,398.019989,398.019989,74092508,404.192502,417.293445,391.091559,0.0,0.0